import "./globals.css";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

export const metadata = {
  title: "ICE 2024 Research",
  description: "Generated by Create Next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-helvetica-condensed">
        {/* Global Navbar */}

        {/* Main Content */}
        {children}
      </body>
    </html>
  );
}